language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e .
  - pip install flake8
  - pip install coveralls
script:
  - flake8 --exclude radixdlt/universe/alphanet_raw.py,radixdlt/universe/sunstone_raw.py,.eggs --max-line-length=120
  - coverage run --source=radixdlt setup.py test
  - coveralls
