language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_script:
  - sudo apt-get install pylint
install:
  - pip install -e .
script:
  - python setup.py test
  - pylint **/*.py